networks:
  expense: {}
volumes:
  mysql:
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
    - expense
    volumes:
      - mysql:/var/lib/mysql
  backend:
    image: backend:1.0.0
    command : sh -c "sleep 5 && node /opt/backend/index.js"
    container_name: backend
    networks:
    - expense
    depends_on:
      - mysql
  frontend:
    image: frontend:1.0.0
    container_name: frontend
    networks:
    - expense
    depends_on:
      - backend
    ports:
      - "80:80"
